apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: parsingNode
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080

---
apiVersion: v1
kind: Pod
metadata:
  name: parsing-pod
  labels:
    app: parsingNode
spec:
  containers:
  - name: main-server
    image: baesuhan0822/micro_service_programming:fastapi
    ports:
    - containerPort: 8000
    imagePullPolicy: Always

  - name: parser-server
    image: baesuhan0822/micro_service_programming:parser
    ports:
    - containerPort: 9000
    imagePullPolicy: Always

  - name: llm-parser-server
    image: baesuhan0822/micro_service_programming:friendly_parsing
    ports:
    - containerPort: 7000
    imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  type: ClusterIP
  selector:
    app: llm
  ports:
  - name: http
    protocol: TCP
    port: 6000
    targetPort: 6000

---
apiVersion: v1
kind: Pod
metadata:
  name: llm-pod
  labels:
    app: llm
spec:
  initContainers:
  - name: init-chroma
    image: baesuhan0822/micro_service_programming:llm
    command: ["sh","-c","cp -r /LLM/chroma-db/* /copy/"]
    volumeMounts:
    - name : chroma-db
      mountPath: /copy
    imagePullPolicy: Always

  containers:
  - name: llm-server
    image: baesuhan0822/micro_service_programming:llm
    ports:
    - containerPort: 6000
    volumeMounts:
    - name: chroma-db
      mountPath: /LLM/chroma-db
    imagePullPolicy: Always

  - name: ollama
    image: ollama/ollama:0.3.2
    ports:
      - containerPort: 11434
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "sleep 5; ollama pull tinyllama:1.1b"]
    env:
      - name: OLLAMA_HOST
        value: "0.0.0.0"
      - name: OLLAMA_CTX_SIZE 
        value: "1024"
    volumeMounts:
      - name: ollama-models
        mountPath: /root/.ollama
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2"

  volumes:
  - name: chroma-db
    emptyDir : {}
  
  - name: ollama-models
    emptyDir: {}